import { ReactElement } from "react";
import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";

import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import { Hello, Travel, Skill, Photo } from "@/components/home";
import { HomeLayout } from "@/layouts";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="font-serif">
        <Hello />
        <Travel />
        <Skill />
        <Photo />
      </div>
    </>
  );
};

Home.getLayout = (page: ReactElement) => <HomeLayout>{page}</HomeLayout>;

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? "en", ["common", "home"])),
    },
  };
};

export default Home;
