import { type ReactNode } from "react";
import type { Metadata } from "next";

import { Footer } from "@/components";

import "@/styles/globals.css";

interface HomeLayoutProps {
  children: ReactNode;
}

const HomeLayout = ({ children }: HomeLayoutProps) => {
  return (
    <html lang="zh-CN">
      <body>
        <div>
          {/* <Header className="fixed w-full top-0 left-0" /> */}
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default HomeLayout;
