import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";

import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import { Hello, Travel, Skill, Photo } from "@/components/home";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Hello className="content font-serif" />
        <Travel className="content font-serif" />
        <Skill className="content font-serif wrapper-y" />
        <Photo className="content font-serif wrapper-y" />
      </div>
    </>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? "en", ["common", "home"])),
    },
  };
};

export default Home;
