import { type ReactNode } from 'react';

import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';

import { Header, Footer } from '@/components';

import '@/styles/globals.css';

interface RootLayoutProps {
  children: ReactNode;
  params: { locale: string };
}

const RootLayout = async ({
  children,
  params: { locale },
}: RootLayoutProps) => {
  let messages;

  try {
    messages = {
      ...(await import(`../../../messages/${locale}/common.json`)).default,
      home: (await import(`../../../messages/${locale}/home.json`)).default,
      about: (await import(`../../../messages/${locale}/about.json`)).default,
    };
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header className="fixed w-full top-0 left-0" />
          <main>{children}</main>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'zh' }];
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default RootLayout;
