import { type ReactNode } from "react";
import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { Footer } from "@/components";

import "@/styles/globals.css";

interface RootLayoutProps {
  children: ReactNode;
  params: { locale: string };
}

const locales = ["en", "zh"];

const RootLayout = ({ children, params: { locale } }: RootLayoutProps) => {
  // Validate that the incoming `locale` parameter is valid
  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) notFound();

  return (
    <html lang={locale}>
      <body>
        {/* <Header className="fixed w-full top-0 left-0" /> */}
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
};

// export function generateStaticParams() {
//   return locales.map((locale) => ({ locale }));
// }

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default RootLayout;
